# Application
spring.application.name=api-gateway
server.port=8080

# Spring Boot Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

# Springdoc / Swagger UI
springdoc.swagger-ui.urls[0].name=Ingestion Service
springdoc.swagger-ui.urls[0].url=/ingestion/v3/api-docs

springdoc.swagger-ui.urls[1].name=User Service
springdoc.swagger-ui.urls[1].url=/user/v3/api-docs

# Gateway HTTP client
spring.cloud.gateway.server.webflux.httpclient.connect-timeout=1000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=5s

# Gateway Routes
spring.cloud.gateway.server.webflux.routes[0].id=ingestion-service-api
spring.cloud.gateway.server.webflux.routes[0].uri=${INGESTION_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/notifications/**

spring.cloud.gateway.server.webflux.routes[1].id=user-service-api
spring.cloud.gateway.server.webflux.routes[1].uri=${USER_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.server.webflux.routes[2].id=ingestion-service-support
spring.cloud.gateway.server.webflux.routes[2].uri=${INGESTION_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/ingestion/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[3].id=user-service-support
spring.cloud.gateway.server.webflux.routes[3].uri=${USER_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/user/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=StripPrefix=1
