# Dispatcher service configuration
spring.application.name=dispatcher-service
server.port=8080

# Actuator endpoints exposure
management.endpoints.web.exposure.include=health

# HTTP client configuration
spring.http.clients.connect-timeout=2s
spring.http.clients.read-timeout=5s

# Custom properties
services.user.url: ${USER_SERVICE_URL}
