# Application
spring.application.name=ingestion-service
server.port=8080

# Spring Boot Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

# Custom properties
services.dispatcher.url: ${DISPATCHER_SERVICE_URL}
